services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - db:/data/postgres
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db

  redis:
    image: redis:7.0-alpine
    container_name: redis-att
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis:/data
  redisinsight:
    image: redis/redisinsight:2.70
    container_name: redisinsight
    ports:
      - 5540:5540
volumes:
  db:
  redis:
